name: secure_cloud_platform
description: A secure cloud platform for managing multiple cloud drives.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  supabase_flutter: ^2.0.0
  file_picker: ^8.3.7
  path_provider: ^2.1.1
  desktop_drop: ^0.7.0
  url_launcher: ^6.2.1
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true